### ISSUE TITLE
Unable to launch Assetfinder

### ISSUE THREAD

**Issue by etaylor77** [tomnomnom/assetfinder#12]
Got a new and fully updated Ubuntu 18.04 server and installed the latest version of Go. However I can not seem to be able to launch the script. I don't see a actual assetfinder.go file, and unable to run the other go files either.

![image](https://user-images.githubusercontent.com/12686164/66363840-9d2d6280-e955-11e9-8904-22c8ebe6eb44.png)

**Comment by teejayen** [comment]
Is *go* in your PATH? If not, try running the binary directly from `~/go/bin/`.

**Comment by etaylor77** [comment]
Thanks, that solved it.

**Comment by teejayen** [comment]
Awesome @etaylor77  - do you mind closing out this issue now?
