### ISSUE TITLE
I can not install it on my ubuntu 16.04

### ISSUE THREAD

**Issue by y0sua** [tomnomnom/assetfinder#15]
# github.com/tomnomnom/assetfinder
/root/go/src/github.com/tomnomnom/assetfinder/urlscan.go:46: u.Hostname undefined (type *url.URL has no field or method Hostname)
/root/go/src/github.com/tomnomnom/assetfinder/urlscan.go:55: u.Hostname undefined (type *url.URL has no field or method Hostname)
/root/go/src/github.com/tomnomnom/assetfinder/wayback.go:38: u.Hostname undefined (type *url.URL has no field or method Hostname)

What's wrong with my machine ? any hints ?

**Comment by prial261** [comment]
Facing this same error on my VPS too , I am also using ubuntu 16

**Comment by tomnomnom** [comment]
Hey! 

This is because you are running an old version of Go. Please update to the latest version of Go and try again!

The `Hostname` field was added in Go 1.8 if I recall correctly, but the latest version of Go (currently 1.14) is almost always preferable.
