### ISSUE TITLE
How can I print the log into .txt file

### ISSUE THREAD

**Issue by y0sua** [tomnomnom/assetfinder#16]
Can we print the log into the .txt file ? ex: assetfinder --subs-only asd.com -o asd.txt

**Comment by EdOverflow** [comment]
You can pipe the output into a text file.

```
$ assetfinder example.com | tee output.txt
$ assetfinder example.com > output.txt
```

Please refer to https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file for more information on how this works.
