### ISSUE TITLE
Assetfinder Error

### ISSUE THREAD

**Issue by phspade** [tomnomnom/assetfinder#20]
Hi @tomnomnom 

Command1: `assetfinder -subs-only domain.com`
Command2: `assetfinder --subs-only domain.com`
Command3: `assetfinder domain.com`
```
panic: runtime error: index out of range [1] with length 1

goroutine 14 [running]:
main.fetchBufferOverrun(0xc000014390, 0xa, 0x18, 0x1, 0x1, 0xc0000189c0, 0x18)
	/root/go/src/github.com/tomnomnom/assetfinder/bufferoverrun.go:23 +0x346
main.main.func1(0xc000014380, 0xc00000e2a0, 0x717520, 0xc000014390, 0xa, 0xc00001e180)
	/root/go/src/github.com/tomnomnom/assetfinder/main.go:61 +0x123
created by main.main
	/root/go/src/github.com/tomnomnom/assetfinder/main.go:57 +0x385
```

**Comment by soupnatzi** [comment]
did you find any resolution for this this just started happening to also? @phspade

**Comment by estebancano-dev** [comment]
i have the same issue. Happens with domains with huge scope (example paypal.com)

**Comment by phspade** [comment]
> did you find any resolution for this just started happening to also? @phspade

Still having an error.

> I have the same issue. Happens with domains with a huge scope (example paypal.com)

Actually, Its paypal.com hahahaha

**Comment by tomnomnom** [comment]
Hey all! Sorry this took me a while to fix, but it should be fine now :)

**Comment by soupnatzi** [comment]
all fixed thanks @tomnomnom
