### ISSUE TITLE
Guide to install it on linux

### ISSUE THREAD

**Issue by knassar702** [tomnomnom/assetfinder#9]
Hello.. i use kali linux 2019 and when install assetfinder i have this error 

my command 
````
root@kali :#~ go run main.go 
# command-line-arguments
./main.go:31:3: undefined: fetchCertSpotter
./main.go:32:3: undefined: fetchHackerTarget
./main.go:33:3: undefined: fetchThreatCrowd
./main.go:34:3: undefined: fetchCrtSh
./main.go:35:3: undefined: fetchFacebook
./main.go:37:3: undefined: fetchVirusTotal
./main.go:38:3: undefined: fetchFindSubDomains
./main.go:39:3: undefined: fetchUrlscan
./main.go:40:3: undefined: fetchBufferOverrun
./main.go:47:8: undefined: newRateLimiter
./main.go:47:8: too many errors
````

**Comment by teejayen** [comment]
Do you get the same errors if you use the binary from `~/go/bin`?

**Comment by knassar702** [comment]
i install go using this command

````
$ apt install golang
````

**Comment by nerdyamigo** [comment]
I installed go using this guide: https://www.digitalocean.com/community/tutorials/how-to-install-go-and-set-up-a-local-programming-environment-on-ubuntu-18-04

after u install go ^ and set up `$GOPATH ` you should be able to run: `go get -u github.com/tomnomnom/assetfinder` and call it just like `assetfinder` 

be sure to install the latest GO version

**Comment by knassar702** [comment]
oh .. i forget this command
````
export PATH=$PATH:$GOPATH/bin
````

Thanks Guys :)

**Comment by 0xm6r** [comment]
I have such an erroe and i couldn't solve it tired
